services:
  postgres:
    image: postgres:15
    container_name: eventhub-db
    environment:
      POSTGRES_DB: eventhub
      POSTGRES_USER: eventhub_user
      POSTGRES_PASSWORD: eventhub_pass
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    container_name: eventhub-adminer
    ports:
      - "8081:8080"